name: Creditoro API unittests.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with docker-compose and run unit tests.
      - run: |
          docker network create web
          docker-compose up -d --build
          docker-compose exec -T creditoro_api flask db upgrade
          docker-compose exec -T creditoro_api pip install -r dev-requirements.txt
          docker-compose exec -T creditoro_api coverage run -m unittest discover
          docker-compose exec -T creditoro_api coverage xml
          docker-compose exec -T creditoro_api pylint --exit-zero src > pylint_report.txt
          docker cp "$(docker-compose ps -q creditoro_api)":/usr/src/app/coverage.xml coverage.xml
      - uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tag-image:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2
      - name: Tag image
        run: |
          echo -n ${{ secrets.DOCKER_HUB_PASS }} | docker login -u creditoro --password-stdin
          docker build -t creditoro/api:production -f docker/Dockerfile .
          docker push creditoro/api:production